config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("shahvani.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("story/", include("shahvani.storys.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

shahvani/storys/urls.py
from django.urls import path
from shahvani.storys import views

app_name = "story"

urlpatterns = [
    path("<int:pk>", views.DetailStoryView.as_view(), name="detail"),
    path("", views.ListStoryView.as_view(), name="list"),
    path('search/', views.SearchView.as_view(), name='search'),
]

shahvani/users/urls.py
from django.urls import path

from shahvani.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

shahvani/storys/models.py
from django.db import models



class StoryModel(models.Model):
    title = models.CharField(max_length=150)
    # views = models.IntegerField()
    link = models.CharField(max_length=500)
    content = models.TextField()
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True, blank=True, null=True)
    tag = models.ManyToManyField("storys.TagModel")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class TagModel(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True, blank=True, null=True)

    class Meta:
        verbose_name = ("TagModel")
        verbose_name_plural = ("TagModels")

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse("TagModel_detail", kwargs={"pk": self.pk})


# for tag in TagModel.objects.all():
#     print(tag.story.all.count())

shahvani/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for Shahvani.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

shahvani/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

shahvani/storys/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from django.db.models import Q 
from rest_framework.views import APIView
from rest_framework.response import Response

from shahvani.storys.models import StoryModel, TagModel
from shahvani.storys.documents import StoryDocument
from shahvani.storys.serilizers import StorySerializer

from elasticsearch_dsl import Search
from elasticsearch_dsl.query import MultiMatch, Match
from django.http import JsonResponse

class DetailStoryView(DetailView):
    model = StoryModel
    template_name = "storys/detail.html"
    context_object_name = "story"


class ListStoryView(ListView):
    model = StoryModel
    template_name = "storys/list.html"
    context_object_name = "storys"
    paginate_by = 21


    def get_queryset(self):
        search = self.request.GET.get('q', '')
        if search:
            query = MultiMatch(query=search, fields=['title'], operator="and", fuzziness="1")
            s = StoryDocument.search().query(query)[:28].execute()

            hits = []
            for hit in s.hits:
                result = {
                    'id': hit.meta.id,
                    'title': hit.title,
                    'content': hit.content[:80]
                }
                hits.append(result)
            return hits
        return super().get_queryset()
    

    def render_to_response(self, context):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse(context["object_list"], safe=False)
        else:
            return super().render_to_response(context)


class SearchView(APIView):
    def get(self, request):
        search = request.GET.get('q', '')
        query = Match(title=search)
        s = StoryDocument.search().query(query)[:10].execute()

        hits = []
        for hit in s.hits:
            result = {
                'title': hit.title
            }
            hits.append(result)

        return Response(hits)


# from django.template.defaultfilters import slugify
# json_file = open("shahvani\\storys\\all_data.json", "r", encoding="utf-8")
# storys = json.load(json_file)

# for index, story in enumerate(storys):
#     try:
#         story_obj = StoryModel.objects.get_or_create(title=story["title"], link=story["link"], content=story["content"])[0]
#         for tag in story["tags"]:
#             tag = TagModel.objects.get_or_create(title=tag)[0]
#             story_obj.tag.add(tag)
#             tag.save()
#             story_obj.save()
#         print("[+] Create Story", index)    
#     except:
#         print("[!] Erorr Story", index)    

shahvani/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

shahvani/templates/storys/list.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
<link href="{% static 'css/plugins/suggestion-box.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}


<section class="page-title bg-cover" style="background:url({% static 'img/sexy/02.jpg' %})no-repeat;" data-overlay="8">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                
                <div class="breadcrumbs-wrap">
                    <h1 class="breadcrumb-title text-light font-2">لیست داستان ها</h1>
                    <nav class="transparent">
                        <ol class="breadcrumb p-0">
                            <li class="breadcrumb-item"><a href="#" class="text-light">خانه</a></li>
                            <li class="breadcrumb-item active theme-cl" aria-current="page">لیست داستان ها</li>
                        </ol>
                    </nav>
                </div>
                
            </div>
        </div>
    </div>
</section>

<section class="min">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="short_wraping">
                        <div class="row m-0 align-items-center justify-content-between">
                            <div class="form-group" style="width: 70%; display: flex;">
                                <form id="search-form"  style="width: 100%; display: flex;">
                                    <input autocomplete="off" id="search-input" type="text" class="form-control" placeholder="جستجوی داستان...">
                                    <input type="submit" value="جستجو" class="btn btn_view_story:detail theme-bg text-light"></input>
                                    <div id="search-inputautocomplete-list" class="autocomplete-items global-rtl">

                                    </div>
                                </form>
                            </div>
                        <div class="dlks_152">
                            <div class="shorting-right ml-2">
                                <label>مرتب سازی براساس:</label>
                                <div class="dropdown show">
                                    <a class="btn btn-filter dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span class="selection">امتیاز بالا</span>
                                    </a>
                                    <div class="drp-select dropdown-menu">
                                        <a class="dropdown-item" href="JavaScript:Void(0);">امتیاز بالا</a>
                                        <a class="dropdown-item" href="JavaScript:Void(0);">بازدید بالا</a>
                                        <a class="dropdown-item" href="JavaScript:Void(0);">دوره جدید</a>
                                        <a class="dropdown-item" href="JavaScript:Void(0);">دوره منتخب</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="row" id="search-results">
                <!-- Single Item -->
                {% for story in storys %}    
                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12">
                    <div class="blg_grid_box">
                        <div class="blg_grid_thumb">
                            <a href="{% url 'story:detail' story.id %}"><img src="assets/img/b-1.png" class="img-fluid" alt=""></a>
                        </div>
                        <div class="blg_grid_caption">
                            <div class="blg_title"><h4><a href="{% url 'story:detail' story.id %}">{{story.title}}</a></h4></div>
                            <div class="blg_desc"><p>{{story.content|truncatewords_html:20}}</p></div>
                            {% for tag in story.tag.all %}
                                <div class="blg_tag"><span>{{tag}}</span></div>
                            {% endfor %}
                        </div>

                    </div>
                </div>
                {% endfor %}
            </div>
    
        </div>
        
    </div>
</section>

<style>
    .autocomplete {
  /*the container must be positioned relative:*/
  position: relative;
  display: inline-block;
}
input {
  border: 1px solid transparent;
  background-color: #f1f1f1;
  padding: 10px;
  font-size: 16px;
}
input[type=text] {
  background-color: #f1f1f1;
  width: 100%;
}
input[type=submit] {
  background-color: DodgerBlue;
  color: #fff;
}
.autocomplete-items {
  position: absolute;
  border: 1px solid #d4d4d4;
  border-bottom: none;
  border-top: none;
  z-index: 99;
  /*position the autocomplete items to be the same width as the container:*/
  top: 100%;
  left: 0;
  right: 0;
}
.autocomplete-items div {
  padding: 10px;
  cursor: pointer;
  background-color: #fff;
  border-bottom: 1px solid #d4d4d4;
}
.autocomplete-items div:hover {
  /*when hovering an item:*/
  background-color: #e9e9e9;
}
.autocomplete-active {
  /*when navigating through the items using the arrow keys:*/
  background-color: DodgerBlue !important;
  color: #ffffff;
}

.highlight{
    color: black;
    font-weight: 600;
}
</style>


{% endblock content %}

{% block inline_javascript %}

<script>

$(document).ready(function() {
    $('#search-form').on('submit', function(event) {
        console.log("press");
        event.preventDefault();
        var query = $('#search-input').val();
        console.log(query);
        $.ajax({
            url: '/story',
            data: {
                'q': query
            },
            success: function(data) {
                console.log(data);
                var results = '';
                for (var i=0; i<data.length; i++) {
                    results += `<div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 global-rtl">
                                    <div class="blg_grid_box global-rtl">
                                        <div class="blg_grid_thumb">
                                            <a href="/story/${data[i].content}"><img src="assets/img/b-1.png" class="img-fluid" alt=""></a>
                                        </div>
                                        <div class="blg_grid_caption global-rtl">
                                            <div class="blg_title global-rtl"><h4 class="global-rtl"><a href="/story/${data[i].id}" class="global-rtl">${data[i].title}</a></h4></div>
                                            <div class="blg_desc global-rtl"><p class="global-rtl">${data[i].content}...</p></div>
                                        </div>
                                    </div>
                                </div>`;
                        }
                $('#search-results').html(results);
                var newUrl = '/story'+'/?q='+query;
                history.pushState({path:newUrl},'',newUrl);
            },
            error: function(XMLHttpRequest, textStatus, errorThrown) {
                console.log('Error:', errorThrown);
            }
        });
    });
});

function highlightWords(firstText, secondText) {
    const firstWords = firstText.split(' ');
    const secondWords = secondText.split(' ');
    const highlightedWords = secondWords.map(word => {
        if (firstWords.includes(word)) {
        return `<span class="highlight">${word}</span>`;
        } else {
        return word;
        }
    });
    return highlightedWords.join(' ');
}


function setValue(e) {
    document.querySelector('input').value = e.innerText;
}


$(document).ready(function() {
    var inputField = $('#search-input');
    var inputField = $('#search-input');

    inputField.on('input', function() {
        var query = inputField.val();
        var countries = ``;
        // var suggustionBox = $("#search-inputautocomplete-list");
        var suggustionBox = $("#search-results");
            $.ajax({
                url: '/story',
            data: {
                'q': query
            },
            success: function(data) {
                $.each(data, function(i, suggestion) {
                    // countries += `
                    //                 <div class="global-rtl" onclick='setValue(this)'>
                    //                      ${highlightWords(query, suggestion["title"])}<input type="hidden" value="${suggestion["title"]}">
                    //                 </div>`
                    countries += `<div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 global-rtl">
                                <div class="blg_grid_box global-rtl">
                                    <div class="blg_grid_thumb">
                                        <a href="/story/${suggestion.id}"><img src="assets/img/b-1.png" class="img-fluid" alt=""></a>
                                    </div>
                                    <div class="blg_grid_caption global-rtl">
                                        <div class="blg_title global-rtl"><h4 class="global-rtl"><a href="/story/${suggestion.id}" class="global-rtl">${suggestion.title}</a></h4></div>
                                        <div class="blg_desc global-rtl"><p class="global-rtl">${suggestion.content}...</p></div>
                                    </div>
                                </div>
                            </div>`;
                });
                suggustionBox.html(countries);

            }
            });
            var newUrl = '/story'+'/?q='+query;
            history.pushState({path:newUrl},'',newUrl);

    });
});

</script>
{% endblock inline_javascript %}