config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("shahvani.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("story/", include("shahvani.storys.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

shahvani/storys/urls.py
from django.urls import path
from shahvani.storys import views

app_name = "story"

urlpatterns = [
    path("<int:pk>", views.DetailStoryView.as_view(), name="detail"),
    path("", views.ListStoryView.as_view(), name="list"),
    path('search/', views.SearchView.as_view(), name='search'),
]

shahvani/users/urls.py
from django.urls import path

from shahvani.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

shahvani/storys/models.py
from django.db import models



class StoryModel(models.Model):
    title = models.CharField(max_length=150)
    # views = models.IntegerField()
    link = models.CharField(max_length=500)
    content = models.TextField()
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True, blank=True, null=True)
    tag = models.ManyToManyField("storys.TagModel")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class TagModel(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True, blank=True, null=True)

    class Meta:
        verbose_name = ("TagModel")
        verbose_name_plural = ("TagModels")

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse("TagModel_detail", kwargs={"pk": self.pk})


# for tag in TagModel.objects.all():
#     print(tag.story.all.count())

shahvani/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for Shahvani.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

shahvani/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

shahvani/storys/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from django.db.models import Q 
from rest_framework.views import APIView
from rest_framework.response import Response

from shahvani.storys.models import StoryModel, TagModel
from shahvani.storys.documents import StoryDocument
from shahvani.storys.serilizers import StorySerializer

from elasticsearch_dsl import Search
from elasticsearch_dsl.query import MultiMatch, Match
from django.http import JsonResponse

class DetailStoryView(DetailView):
    model = StoryModel
    template_name = "storys/detail.html"
    context_object_name = "story"


class ListStoryView(ListView):
    model = StoryModel
    template_name = "storys/list.html"
    context_object_name = "storys"
    paginate_by = 21


    def get_queryset(self):
        search = self.request.GET.get('q', '')
        if search:
            query = MultiMatch(query=search, fields=['title'], operator="and", fuzziness="1")
            s = StoryDocument.search().query(query)[:28].execute()

            hits = []
            for hit in s.hits:
                result = {
                    'id': hit.meta.id,
                    'title': hit.title,
                    'content': hit.content[:80]
                }
                hits.append(result)
            return hits
        return super().get_queryset()
    

    def render_to_response(self, context):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse(context["object_list"], safe=False)
        else:
            return super().render_to_response(context)


class SearchView(APIView):
    def get(self, request):
        search = request.GET.get('q', '')
        query = Match(title=search)
        s = StoryDocument.search().query(query)[:10].execute()

        hits = []
        for hit in s.hits:
            result = {
                'title': hit.title
            }
            hits.append(result)

        return Response(hits)


# from django.template.defaultfilters import slugify
# json_file = open("shahvani\\storys\\all_data.json", "r", encoding="utf-8")
# storys = json.load(json_file)

# for index, story in enumerate(storys):
#     try:
#         story_obj = StoryModel.objects.get_or_create(title=story["title"], link=story["link"], content=story["content"])[0]
#         for tag in story["tags"]:
#             tag = TagModel.objects.get_or_create(title=tag)[0]
#             story_obj.tag.add(tag)
#             tag.save()
#             story_obj.save()
#         print("[+] Create Story", index)    
#     except:
#         print("[!] Erorr Story", index)    

shahvani/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

shahvani/templates/base.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="fa">
	
<head>
		<meta charset="utf-8" />
		<meta name="author" content="Themezhub" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Shahvani{% endblock title %}</title>
		 
        <!-- Custom CSS -->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
		    {% block css %}
        {% endblock %}
    </head>
	
    <body dir="rtl">

        <!-- ============================================================== -->
        <!-- Main wrapper - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <div id="main-wrapper">
		
            <!-- ============================================================== -->
            <!-- Top header  -->
            <!-- ============================================================== -->
            <!-- Start Navigation -->
			<div class="header header-light head-shadow global-rtl">
				<div class="container global-rtl">
					<nav id="navigation" class="navigation navigation-landscape">
						<div class="nav-header">
							<a class="nav-brand" href="#">
								<img src="assets/img/logo.png" class="logo" alt="">
							</a>
							<div class="nav-toggle"></div>
							<div class="mobile_nav global-rtl">
								<ul>
									<li>
										<a href="javascript:void(0);" data-toggle="modal" data-target="#login" class="crs_yuo12 w-auto text-white theme-bg global-rtl">
											<span class="embos_45"><i class="fas fa-sign-in-alt ml-1 rotate-img"></i>ورود</span>
										</a>
									</li>
								</ul>
							</div>
						</div>
						<div class="nav-menus-wrapper global-rtl" style="transition-property: none;"><span class="nav-menus-wrapper-close-button">✕</span>
							<ul class="nav-menu">
							
								<li class="active global-rtl"><a href="#" class="global-rtl">خانه<span class="submenu-indicator"></span></a>
									<ul class="nav-dropdown nav-submenu" style="left: auto;">
										<li class="global-rtl"><a href="index.html" class="global-rtl">خانه 1</a></li>
										<li class="global-rtl"><a href="home-2.html" class="global-rtl">خانه 2</a></li>
										<li><a href="home-3.html" class="global-rtl">خانه 3</a></li>
										<li class="global-rtl"><a href="home-4.html" class="global-rtl">خانه 4</a></li>
										<li class="global-rtl"><a href="home-5.html">خانه 5</a></li>
										<li class="global-rtl"><a href="home-6.html" class="global-rtl">خانه 6</a></li>
										<li class="global-rtl"><a href="home-7.html" class="global-rtl">خانه 7</a></li>
									</ul>
								</li>
								
								<li class="global-rtl"><a href="{% url 'story:list' %}" class="global-rtl">داستان ها</a>

								</li>
								
								<li><a href="#" class="global-rtl">عکس ها<span class="submenu-indicator"></span></a>
								</li>
								
								<li class="global-rtl"><a href="dashboard.html" class="global-rtl">حساب کاربری</a></li>
								
							</ul>
							
							<ul class="nav-menu nav-menu-social align-to-left">
								
								<li class="">
									<a href="#" data-toggle="modal" data-target="#login" class="global-rtl">
										<i class="fas fa-sign-in-alt ml-1 rotate-img"></i><span class="dn-lg global-rtl">ورود</span>
									</a>
								</li>
								<li class="add-listing theme-bg global-rtl">
									<a href="signup.html" class="text-white global-rtl">ثبت نام</a>
								</li>
							</ul>
						</div>
					</nav>
				</div>
			</div>
			<!-- End Navigation -->
			<div class="clearfix"></div>
			<!-- ============================================================== -->
			<!-- Top header  -->
			<!-- ============================================================== -->
		</div>
      
	{% if messages %}
        {% for message in messages %}
          <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}

    {% block content %}

    {% endblock content %}
    		
			<!-- ============================ Footer Start ================================== -->
			<footer class="dark-footer skin-dark-footer style-2">
				<div class="footer-middle">
					<div class="container">
						<div class="row">
							
							<div class="col-lg-5 col-md-5">
								<div class="footer_widget">
									<img src="{% static 'img/logo-light.png' %}" class="img-footer small mb-2" alt="" />
									<h4 class="extream mb-3 font-2">آیا به کمک تیم پشتیبانی<br>نیاز دارید؟</h4>
									<p>هر ماه با عضویت در خبرنامه ما از به‌روزرسانی‌ها، معاملات جدید، آموزش‌ها و تخفیف‌ها باخبر شوید.</p>
									<div class="foot-news-last">
										<div class="input-group">
										  <input type="text" class="form-control" placeholder="ایمیل">
											<div class="input-group-append">
												<button type="button" class="input-group-text theme-bg b-0 text-light">عضویت</button>
											</div>
										</div>
									</div>
								</div>
							</div>
							
							<div class="col-lg-6 col-md-7 ml-auto">
								<div class="row">
								
									<div class="col-lg-4 col-md-4">
										<div class="footer_widget">
											<h4 class="widget_title">صفحات</h4>
											<ul class="footer-menu">
												<li><a href="#">صفحه اصلی</a></li>
												<li><a href="#">درباره ما</a></li>
												<li><a href="#">خدمات</a></li>
												<li><a href="#">دوره های آموزشی</a></li>
												<li><a href="#">تماس با ما</a></li>
												<li><a href="#">لیست وبلاگ</a></li>
											</ul>
										</div>
									</div>
											
									<div class="col-lg-4 col-md-4">
										<div class="footer_widget">
											<h4 class="widget_title">تمام بخش ها</h4>
											<ul class="footer-menu">
												<li><a href="#">منو<span class="new">جدید</span></a></li>
												<li><a href="#">ویژگی های جذاب</a></li>
												<li><a href="#">المان ها<span class="new">جدید</span></a></li>
												<li><a href="#">نظرات کاربران</a></li>
												<li><a href="#">ویدئو</a></li>
												<li><a href="#">فوتر</a></li>
											</ul>
										</div>
									</div>
							
									<div class="col-lg-4 col-md-4">
										<div class="footer_widget">
											<h4 class="widget_title">لینک های مفید</h4>
											<ul class="footer-menu">
												<li><a href="#">درباره ما</a></li>
												<li><a href="#">وبلاگ</a></li>
												<li><a href="#">قیمت گذاری</a></li>
												<li><a href="#">ثبت نام</a></li>
												<li><a href="#">ورود به حساب</a></li>
												<li><a href="#">پشتیبانی <span class="update">بروزرسانی</span></a></li>
											</ul>
										</div>
									</div>
									
								</div>
							</div>
						</div>
					</div>
				</div>
				
			</footer>
			<!-- ============================ Footer End ================================== -->
			
			<!-- Log In Modal -->
			<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="loginmodal" aria-hidden="true">
				<div class="modal-dialog modal-xl login-pop-form" role="document">
					<div class="modal-content overli" id="loginmodal">
						<div class="modal-header">
							<h5 class="modal-title">ورود به حساب کاربری</h5>
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							  <span aria-hidden="true"><i class="fas fa-times-circle"></i></span>
							</button>
						  </div>
						<div class="modal-body">
							<div class="login-form">
								<form>
								
									<div class="form-group">
										<label>نام کاربری</label>
										<div class="input-with-icon">
											<input type="text" class="form-control" placeholder="نام کاربری/ ایمیل">
											<i class="ti-user"></i>
										</div>
									</div>
									
									<div class="form-group">
										<label>رمز عبور</label>
										<div class="input-with-icon">
											<input type="password" class="form-control" placeholder="*******">
											<i class="ti-unlock"></i>
										</div>
									</div>
									
									<div class="form-group row">
										<div class="col-xl-4 col-lg-4 col-4">
											<input id="admin" class="checkbox-custom" name="admin" type="checkbox">
											<label for="admin" class="checkbox-custom-label">مدیر</label>
										</div>
										<div class="col-xl-4 col-lg-4 col-4">
											<input id="student" class="checkbox-custom" name="student" type="checkbox" checked>
											<label for="student" class="checkbox-custom-label">هنرجو</label>
										</div>
										<div class="col-xl-4 col-lg-4 col-4">
											<input id="instructor" class="checkbox-custom" name="instructor" type="checkbox">
											<label for="instructor" class="checkbox-custom-label">مدرس</label>
										</div>
									</div>
									
									<div class="form-group">
										<button type="submit" class="btn btn-md full-width theme-bg text-white">ورود به حساب</button>
									</div>
									
									<div class="rcs_log_125 pt-2 pb-3">
										<span>یا ورود از طریق شبکه های اجتماعی</span>
									</div>
									<div class="rcs_log_126 full">
										<ul class="social_log_45 row">
											<li class="col-xl-4 col-lg-4 col-md-4 col-4"><a href="javascript:void(0);" class="sl_btn"><i class="ti-facebook text-info"></i>Facebook</a></li>
											<li class="col-xl-4 col-lg-4 col-md-4 col-4"><a href="javascript:void(0);" class="sl_btn"><i class="ti-google text-danger"></i>Google</a></li>
											<li class="col-xl-4 col-lg-4 col-md-4 col-4"><a href="javascript:void(0);" class="sl_btn"><i class="ti-twitter theme-cl"></i>Twitter</a></li>
										</ul>
									</div>
								
								</form>
							</div>
						</div>
						<div class="crs_log__footer d-flex justify-content-between mt-0">
							<div class="fhg_45"><p class="musrt">حساب کاربری ندارید؟ <a href="signup.html" class="theme-cl">ثبت نام</a></p></div>
							<div class="fhg_45"><p class="musrt"><a href="forgot.html" class="text-danger">رمز عبور را فراموش کرده اید؟</a></p></div>
						</div>
					</div>
				</div>
			</div>
			<!-- End Modal -->
			
			<a id="back2Top" class="top-scroll" title="Back to top" href="#"><i class="ti-arrow-up"></i></a>
			

		</div>
		<!-- ============================================================== -->
		<!-- End Wrapper -->
		<!-- ============================================================== -->

		<!-- ============================================================== -->
		<!-- All Jquery -->
		<!-- ============================================================== -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/popper.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/select2.min.js' %}"></script>
		<script src="{% static 'js/slick.js' %}"></script>
		<script src="{% static 'js/moment.min.js' %}"></script>
		<script src="{% static 'js/daterangepicker.js' %}"></script> 
		<script src="{% static 'js/summernote.min.js' %}"></script>
		<script src="{% static 'js/metisMenu.min.js' %}"></script>	
		<script src="{% static 'js/custom.js' %}"></script>
		<!-- ============================================================== -->
		<!-- This page plugins -->
		<!-- ============================================================== -->		
    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}

    {% endblock inline_javascript %}
	</body>

</html>